- name: Install Rails Server
  hosts: production
  become: true
  gather_facts: no

  pre_tasks:
    - name: Install make
      apt: name=make

  roles:
    - ruby
    - nginx
    - nodejs
    - monit
    - image_magick
    - postgre
