- name: Install Rails Server
  hosts: staging
  become: true
  gather_facts: no

  # pre_tasks:
  #   - name: apt-get update
  #     raw: apt-get update -qq
  #   - name: install python 2.7
  #     raw: apt-get install -qq python2.7
  #   - name: set python 2.7 as default
  #     raw: update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1

  roles:
    - mysql
    - redis
    - ruby
    - nginx
