- name: Install Nginx
  apt: name=nginx

- name: Copy nginx config file
  template:
    src=templates/nginx_simple_config
    dest=/etc/nginx/sites-available/{{ nginx_app_name }}

- name: Enable configuration
  file:
    src=/etc/nginx/sites-available/{{ nginx_app_name }}
    dest=/etc/nginx/sites-enabled/{{ nginx_app_name }}
    state=link

- name: Restart nginx
  service: name=nginx state=restarted enabled=yes
