- name: Create ruby-install directory
  file: path=/root/ruby-install state=directory

- name: Download and unpack postmodern/ruby-install
  unarchive:
    src: "https://github.com/postmodern/ruby-install/archive/v{{ ruby_install_version }}.tar.gz"
    dest: /root/ruby-install/
    remote_src: true

- name: Install ruby-install
  make:
    chdir=/root/ruby-install/ruby-install-{{ ruby_install_version }}
    target=install

- block:
  - name: Install the specific Ruby version
    command: ruby-install ruby {{ ruby_version }}

  - name: Install Bundler
    gem:
      name=bundler
      version=1.11.2
      executable=~/.rubies/ruby-{{ ruby_version }}/bin/gem
      user_install=no

  - name: Find all files in ruby-{{ ruby_version }}/bin
    find:
      paths: ~/.rubies/ruby-{{ ruby_version }}/bin
    register: ruby_bin_files

  become: false

- name: Add ruby to bin path
  file:
    src="{{ item.path }}"
    dest=/usr/local/bin/{{ item.path | basename }}
    state=link
  with_items: "{{ ruby_bin_files.files }}"
